name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["linux"]
    steps:
      - name: Build
        run: |
          function build() {
            if python server1.py then
              exit 0
            python client1.py      
          }
          export -f build
          parallel -j0 build ::: "amd64" "386"
